version: "3"

services:
    
  rest:
    build: ./rest
    container_name: deno-deploy
    environment:
      - CONTAINERIZED=1
    ports:
      - "10020:15000"
    networks:
      - app-network
    volumes:
      - ./rest/person.db:/app/person.db

  grpc:
    restart: always
    build: ./grpc
    container_name: grpc_dev
    environment:
      - CONTAINERIZED=1
    ports:
      - 10030:13000
    networks:
      - app-network
    volumes:
      - ./grpc/person.db:/usr/src/backend/person.db

  soap:
    build: ./soap
    container_name: soap_dev
    ports:
      - 10040:5000
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"


# Primarily only includes technologies vital to development
