version: "3"

services:
    
  rest:
    build: ./rest
    image: cph-si/rest:v1.0
    container_name: deno-deploy
    environment:
      - CONTAINERIZED=1
    ports:
      - "10020:15000"
    networks:
      - app-network
    volumes:
      - ./rest/data:/app/data

  grpc:
    restart: always
    build: ./grpc
    image: cph-si/grpc:v1.0
    container_name: grpc_dev
    environment:
      - CONTAINERIZED=1
    ports:
      - 10030:13000
    networks:
      - app-network
    volumes:
      - ./grpc/migration/data:/usr/src/backend/migration/data

  soap:
    build: ./soap
    image: cph-si/soap:v1.0
    container_name: soap_dev
    ports:
      - 10040:5000
    networks:
      - app-network

  bus:
    build: ./bus
    image: cph-si/bus:v1.0
    container_name: bus
    ports:
      - 10060:3030
    networks:
      - app-network
    
  gateway:
    build: ./gateway
    image: cph-si/gateway:v1.0
    container_name: gateway
    ports:
      - 10100:10000
    networks:
      - app-network

  grpc-migration:
    build: ./grpc/migration
    image: cph-si/grpc-migration:v1.0
    volumes:
      - ./grpc/migration/data:/usr/src/app/data
    environment:
      - CONTAINERIZED=1

  rest-migration:
    build: ./rest/migration
    image: cph-si/rest-migration:v1.0
    volumes:
      - ./rest/migration/data:/usr/src/app/data
    environment:
      - CONTAINERIZED=1

  soap-migration:
    build: ./soap/migration
    image: cph-si/soap-migration:v1.0
    volumes:
      - ./soap/src:/usr/src/app/data
    environment:
      - CONTAINERIZED=1

networks:
  app-network:
    driver: "bridge"


# Primarily only includes technologies vital to development
