version: "3"

services:
    
  rest:
    build: ./rest
    image: si-miniproj-rest:0.0.1
    container_name: deno-deploy
    environment:
      - CONTAINERIZED=1
    ports:
      - "10020:15000"
    networks:
      - app-network
    volumes:
      - ./rest/data:/app/data

  grpc:
    restart: always
    build: ./grpc
    image: si-miniproj-grpc:0.0.1
    container_name: grpc_dev
    environment:
      - CONTAINERIZED=1
    ports:
      - 10030:13000
    networks:
      - app-network
    volumes:
      - ./grpc/data:/usr/src/backend/data

  soap:
    build: ./soap
    container_name: soap_dev
    ports:
      - 10040:5000
    networks:
      - app-network

  bus:
    build: ./bus
    image: si-miniproj-bus:0.0.1
    ports:
      - 10060:10060
    networks:
      - app-network
    
  gateway:
    build: ./gateway
    image: si-miniproj-gateway:0.0.1
    ports:
      - 10000:10000
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"


# Primarily only includes technologies vital to development
