[server]
host="0.0.0.0"
port=10000

[clients]

[clients.rest]
[clients.rest.mini-proj]
host = "deno-deploy"
port = 10050


[clients.soap]
[clients.soap.mini-proj]
host="localhost"
port=10040


[clients.grpc]
[clients.grpc.mini-proj]
host="grpc_dev"
port=10030

[clients.bus]
[clients.bus.mini-proj]
host="localhost"
port=3030