# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import person_pb2 as person__pb2


class PersonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePerson = channel.unary_unary(
                '/person.Person/CreatePerson',
                request_serializer=person__pb2.CreatePersonRequest.SerializeToString,
                response_deserializer=person__pb2.CreatePersonResponse.FromString,
                )
        self.ReadPerson = channel.unary_unary(
                '/person.Person/ReadPerson',
                request_serializer=person__pb2.ReadPersonRequest.SerializeToString,
                response_deserializer=person__pb2.ReadPersonResponse.FromString,
                )
        self.UpdatePerson = channel.unary_unary(
                '/person.Person/UpdatePerson',
                request_serializer=person__pb2.UpdatePersonRequest.SerializeToString,
                response_deserializer=person__pb2.UpdatePersonResponse.FromString,
                )
        self.DeletePerson = channel.unary_unary(
                '/person.Person/DeletePerson',
                request_serializer=person__pb2.DeletePersonRequest.SerializeToString,
                response_deserializer=person__pb2.DeletePersonResponse.FromString,
                )
        self.ReadPersonList = channel.unary_unary(
                '/person.Person/ReadPersonList',
                request_serializer=person__pb2.ReadPersonListRequest.SerializeToString,
                response_deserializer=person__pb2.ReadPersonListResponse.FromString,
                )
        self.ReadPersonListByIDList = channel.unary_unary(
                '/person.Person/ReadPersonListByIDList',
                request_serializer=person__pb2.ReadPersonListByIDListRequest.SerializeToString,
                response_deserializer=person__pb2.ReadPersonListByIDListResponse.FromString,
                )


class PersonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPersonList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPersonListByIDList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePerson': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePerson,
                    request_deserializer=person__pb2.CreatePersonRequest.FromString,
                    response_serializer=person__pb2.CreatePersonResponse.SerializeToString,
            ),
            'ReadPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPerson,
                    request_deserializer=person__pb2.ReadPersonRequest.FromString,
                    response_serializer=person__pb2.ReadPersonResponse.SerializeToString,
            ),
            'UpdatePerson': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePerson,
                    request_deserializer=person__pb2.UpdatePersonRequest.FromString,
                    response_serializer=person__pb2.UpdatePersonResponse.SerializeToString,
            ),
            'DeletePerson': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePerson,
                    request_deserializer=person__pb2.DeletePersonRequest.FromString,
                    response_serializer=person__pb2.DeletePersonResponse.SerializeToString,
            ),
            'ReadPersonList': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPersonList,
                    request_deserializer=person__pb2.ReadPersonListRequest.FromString,
                    response_serializer=person__pb2.ReadPersonListResponse.SerializeToString,
            ),
            'ReadPersonListByIDList': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPersonListByIDList,
                    request_deserializer=person__pb2.ReadPersonListByIDListRequest.FromString,
                    response_serializer=person__pb2.ReadPersonListByIDListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'person.Person', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Person(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/person.Person/CreatePerson',
            person__pb2.CreatePersonRequest.SerializeToString,
            person__pb2.CreatePersonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/person.Person/ReadPerson',
            person__pb2.ReadPersonRequest.SerializeToString,
            person__pb2.ReadPersonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/person.Person/UpdatePerson',
            person__pb2.UpdatePersonRequest.SerializeToString,
            person__pb2.UpdatePersonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/person.Person/DeletePerson',
            person__pb2.DeletePersonRequest.SerializeToString,
            person__pb2.DeletePersonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadPersonList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/person.Person/ReadPersonList',
            person__pb2.ReadPersonListRequest.SerializeToString,
            person__pb2.ReadPersonListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadPersonListByIDList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/person.Person/ReadPersonListByIDList',
            person__pb2.ReadPersonListByIDListRequest.SerializeToString,
            person__pb2.ReadPersonListByIDListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
