[default]

[default.grpc]
host="localhost"
port=13000

[default.rest]
host="localhost"
port=15000

[default.server]
host=[0,0,0,0]
port=3030

[containerized]

[containerized.grpc]
host="grpc-service"
port=80

[containerized.rest]
host="rest-service"
port=80

[containerized.server]
host=[0,0,0,0]
port=3030

