
[database]
port=15100
user="test_user"
pass="test_pass"
db ="..data/rest"
host="localhost"
max_pool_connections=20

# From root of project. See utils/aliases.py
[misc]
migrations_folder="/migrations"