apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-deploy
spec:
  selector:
    matchLabels:
      app: bus
  template:
    metadata:
      labels:
        app: bus
    spec:
      containers:
      - name: bus
        image: cph-si/bus:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: CONTAINERIZED
            value: "1"
        ports:
        - containerPort: 10060
