apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      volumes:
        - name: persondb
          hostPath:
            path: /srv/db/person
            type: DirectoryOrCreate
      containers:
      - name: grpc
        image: cph-si/grpc:v1.0
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /usr/src/backend/migration/data
            name: persondb
        ports:
        - containerPort: 13000
