
[development]
[development.database]
port=15100
user="test_user"
pass="test_pass"
db ="../person"
host="localhost"
max_pool_connections=20

[containerized]
[containerized.database]
port=5432
user="test_user"
pass="test_pass"
db ="../person"
host="primary_db"
max_pool_connections=20



# From root of project. See utils/aliases.py
[misc]
migrations_folder="/migrations"